version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-kgs-db
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/shLxl@2025 # <-- 重要：请将这里的密码替换为您自己的强密码

volumes:
  neo4j-data:
